In [1]:
import numpy as np

In [2]:
# LU_decomposition
A = np.array([[3.,5.],[6.,7.]])

def LU_decomposition(A):
    U = A
    L = np.eye(A.shape[1])
    for i in range(A.shape[1]):
        tmp = np.eye(A.shape[0])
        tmp1 = np.eye(A.shape[0])
        for j in range(i+1, A.shape[0]):
            tmp[j][i] =0 -U[j][i]/U[i][i]
            tmp1[j][i] = U[j][i]/U[i][i]
            L[j][i] = U[j][i]/U[i][i]
        U = tmp@U
        # print("M_"+str(i))
        # print(tmp)
        # print("M^-1_"+str(i))
        # print(tmp1)
    return L, U

L, U = LU_decomposition(A)

print(L)
print(U)
print(L@U)

import numpy as np

def LU_decomposition_chop(A, precision=3):
    U = A.copy()
    L = np.eye(A.shape[0])

    for i in range(A.shape[0]):
        tmp = np.eye(A.shape[0])

        for j in range(i + 1, A.shape[0]):
            factor = round(U[j][i] / U[i][i], precision)
            tmp[j][i] = -factor
            L[j][i] = factor

        U = tmp @ U

    # Apply chopping to U
    # U = np.round(U, decimals=precision)

    return L, U

# Example usage
A = np.array([[0.03, 58.9], [5.31, -6.10]])

L, U = LU_decomposition_chop(A, precision=3)

print("L:")
print(L)
print("U:")
print(U)

[[1. 0.]
 [2. 1.]]
[[ 3.  5.]
 [ 0. -3.]]
[[3. 5.]
 [6. 7.]]
L:
[[  1.   0.]
 [177.   1.]]
U:
[[ 3.00000e-02  5.89000e+01]
 [ 0.00000e+00 -1.04314e+04]]


In [6]:
# back substitution
def BS_solving(Tri_A, b):
    ans = np.zeros(len(b))
    for i in range(len(b)):
        index = len(b)-1-i
        if i == 0:
            ans[index] = b[index]/Tri_A[index][index]
        else:
            partial_sum = 0
            for j in range(index, len(b)):
                partial_sum += Tri_A[index][j] * ans[j]
            ans[index] = (b[index]-partial_sum)/Tri_A[index][index]
    return ans

In [14]:
# one general solving kernel.
# np.set_printoptions(precision=2, suppress=True, formatter={'float': '{:0.3e}'.format})
def General_Solving(A,b):
    # L, U = LU_decomposition(A)
    L, U = LU_decomposition_chop(A)
    print(L)
    print(U)
    L_inv = np.linalg.inv(L)
    b_new = L_inv@b.T
    b_sol = b_new.T
    return BS_solving(U, b_sol)


A = np.array([[3.03,-12.1,14], [-3.03, 12.1, -7], [6.11,-14.2,21]])
b = np.array([-119,120,-139])
L,U = LU_decomposition(A)

print(np.linalg.inv(L)@b)

# x = np.linalg.solve(A, b)


[nan nan nan]


C:\Users\Jiadong Hong\AppData\Local\Temp\ipykernel_28932\1021947919.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  tmp[j][i] = -U[j][i]/U[i][i]
C:\Users\Jiadong Hong\AppData\Local\Temp\ipykernel_28932\1021947919.py:12: RuntimeWarning: divide by zero encountered in double_scalars
  tmp1[j][i] = U[j][i]/U[i][i]
C:\Users\Jiadong Hong\AppData\Local\Temp\ipykernel_28932\1021947919.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  L[j][i] = U[j][i]/U[i][i]
C:\Users\Jiadong Hong\AppData\Local\Temp\ipykernel_28932\1021947919.py:14: RuntimeWarning: invalid value encountered in matmul
  U = tmp@U


In [20]:
def gaussian_elimination(A, b):
    # 合并增广矩阵
    augmented_matrix = np.column_stack((A, b))

    # 行数和列数
    rows, cols = augmented_matrix.shape

    for i in range(rows):
        # 首先进行列主元素的选取
        max_row = np.argmax(np.abs(augmented_matrix[i:, i])) + i
        augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]]

        # 将当前列的主元素缩放为1
        augmented_matrix[i] /= augmented_matrix[i, i]

        # 将其他行的当前列清零
        for j in range(i + 1, rows):
            augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]

    augmented_matrix = np.round(augmented_matrix,decimals=3)
    print(augmented_matrix)

    # 回代求解
    x = np.zeros(rows)
    for i in range(rows - 1, -1, -1):
        x[i] = augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i+1:cols-1], x[i+1:])

    return x

A = np.array([[3.03,-12.1,14], [-3.03, 12.1, -7], [6.11,-14.2,21]])
b = np.array([-119,120,-139])
gaussian_elimination(A,b)

[[  1.     -2.324   3.437 -22.75 ]
 [  0.      1.      0.675  10.096]
 [  0.      0.      1.      0.143]]


array([-2.711100e-03,  9.999475e+00,  1.430000e-01])

In [153]:
# Linear_Least_Square
# house holder transformation & QR factorization.
# H = np.eye(2) - 2*(A[:,[0]]@A[:,[0]].T)/(A[:,[0]].T@A[:,[0]])
def householder(a):
    e = np.zeros_like(a)
    e[0] = 1
    print(e)
    tmp = a - np.linalg.norm(a)*e
    x = tmp/np.linalg.norm(tmp)
    # print(np.linalg.norm(x))
    print(np.eye(a.shape[0]))
    H = np.eye(a.shape[0]) - 2*np.outer(x,x)
    print(H)
    output = H@a
    return output

a = np.array([[1],[3],[5]])
householder(a)



[[1]
 [0]
 [0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.16903085  0.50709255  0.84515425]
 [ 0.50709255  0.69055066 -0.5157489 ]
 [ 0.84515425 -0.5157489   0.14041849]]


array([[5.91607978e+00],
       [0.00000000e+00],
       [1.11022302e-16]])

In [214]:
import numpy as np

def qr_householder(A):
    m, n = A.shape
    Q = np.eye(m)
    for i in range(n - (m == n)):
        x = A[i:, i]
        e = np.zeros_like(x)
        e[0] = np.copysign(np.linalg.norm(x), x[0])
        v = x - e
        H = np.eye(m)
        H[i:, i:] -= 2 * np.outer(v, v) / np.dot(v,v)
        print(H)
        A = np.dot(H, A)
        print(A)
        Q = np.dot(Q, H)
    R = np.triu(A)
    return Q, R

A = np.array([[1, 1, 1], [1, 2, 4], [1,3,9],[1,4,16]])
Q, R = qr_householder(A)
print(Q)
print(R)
Q@R

[[ 0.5  0.5  0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]
[[  2.   5.  15.]
 [  0.  -2. -10.]
 [  0.  -1.  -5.]
 [  0.   0.   2.]]
[[ 1.          0.          0.          0.        ]
 [ 0.          0.89442719  0.4472136   0.        ]
 [ 0.          0.4472136  -0.89442719  0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 2.00000000e+00  5.00000000e+00  1.50000000e+01]
 [ 0.00000000e+00 -2.23606798e+00 -1.11803399e+01]
 [ 0.00000000e+00 -3.33066907e-16 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+00]]
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  8.8817842e-16 -1.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -1.0000000e+00 -8.8817842e-16]]
[[ 2.00000000e+00  5.00000000e+00  1.50000000e+01]
 [ 0.00000000e+00 -2.23606798e+00 -1.11803399e+01]
 [ 0.00000000e+00 -2.95822839e-31 -2.00000000e+00]
 [ 0.00000000e+00 

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.]])

In [189]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([1, 2, 300])
# normal equation.
w = np.linalg.inv(X.T @ X) @ X.T @ y
y_pred = X @ w
resid = y - y_pred
print(w)

print(np.linalg.norm(resid))

[ 198.   -123.25]
121.24974226776737


In [195]:
Q, R = qr_householder(A)
new_y = Q.T@y
np.abs(new_y[-1])

177.31562729542006

In [203]:
np.linalg.norm(Q.T@X@w - new_y)

121.24974226776737

In [202]:
np.linalg.norm(Q.T@(X@w - y))

121.24974226776737

In [207]:
5*np.cos(1)*10**(-6)

2.7015115293406988e-06