In [11]:
# LU Decomposition
import numpy as np
from scipy.linalg import lu
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
p, l, u = lu(A)
PL, U = lu(A, permute_l=True)
print(PL)
print(U)

[[ 0.28571429  1.          0.          0.        ]
 [ 0.71428571 -0.44       -0.46153846  1.        ]
 [ 1.          0.          0.          0.        ]
 [ 0.71428571  0.12        1.          0.        ]]
[[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]]


In [32]:
#coding:utf8
import numpy as np

# def gram_schmidt(A):
#     """Gram-schmidt正交化"""
#     Q=np.zeros_like(A)
#     cnt = 0
#     for a in A.T:
#         u = np.copy(a)
#         for i in range(0, cnt):
#             u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) # 减去待求向量在以求向量上的投影
#         e = u / np.linalg.norm(u)  # 归一化
#         Q[:, cnt] = e
#         cnt += 1
#     R = np.dot(Q.T, A)
#     return (Q, R)

# def givens_rotation(A):
#     """Givens变换"""
#     (r, c) = np.shape(A)
#     Q = np.identity(r)
#     R = np.copy(A)
#     (rows, cols) = np.tril_indices(r, -1, c)
#     for (row, col) in zip(rows, cols):
#         if R[row, col] != 0:  # R[row, col]=0则c=1,s=0,R、Q不变
#             r_ = np.hypot(R[col, col], R[row, col])  # d
#             c = R[col, col]/r_
#             s = -R[row, col]/r_
#             G = np.identity(r)
#             G[[col, row], [col, row]] = c
#             G[row, col] = s
#             G[col, row] = -s
#             R = np.dot(G, R)  # R=G(n-1,n)*...*G(2n)*...*G(23,1n)*...*G(12)*A
#             Q = np.dot(Q, G.T)  # Q=G(n-1,n).T*...*G(2n).T*...*G(23,1n).T*...*G(12).T
#     return (Q, R)

def householder_reflection(A):
    """Householder变换"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    H_list = []
    for cnt in range(r - 1):
        x = R[cnt:, cnt]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_cnt = np.identity(r)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_cnt, R)  # R=H(n-1)*...*H(2)*H(1)*A
        Q = np.dot(Q, Q_cnt)  # Q=H(n-1)*...*H(2)*H(1)  H为自逆矩阵
        H_list.append(Q_cnt)
    return (Q, R, H_list)


In [33]:
np.set_printoptions(precision=4, suppress=True)
#A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 7], [4, 2, 1]])
A = np.array([[1, -1, 4], [1, 4, -2], [1, 4, 2], [1, -1, 0]])
#A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]],dtype=float)

# (Q, R) = gram_schmidt(A)
# print(Q)
# print(R)
# print(np.dot(Q,R))

# (Q, R) = givens_rotation(A)
# print(Q)
# print(R)
# print(np.dot(Q,R))

(Q, R, H) = householder_reflection(A)
print(Q)
print(R)
print(H)
print(np.dot(Q,R))

[[ 0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]
 [ 0.5  0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5 -0.5]]
[[ 2.  3.  2.]
 [ 0.  5. -2.]
 [ 0.  0.  4.]
 [ 0.  0. -0.]]
[array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5,  0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5]]), array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.]]), array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.]])]
[[ 1. -1.  4.]
 [ 1.  4. -2.]
 [ 1.  4.  2.]
 [ 1. -1.  0.]]
